import convertPxToDp from './ConvertPxToDp';
import {useTheme} from '@theme/ThemeProvider';

const {theme} = useTheme();

// iconData.json
const iconData = {
  dashboard: {
    type: 'svg',
    source: require('@assets/icons/dashboard.js'),
    width: convertPxToDp(46),
    height: convertPxToDp(46),
    color: theme.colors.primary,
  },
  'dashboard-outline': {
    type: 'svg',
    source: require('@assets/icons/dashboard-outline.js'),
    width: convertPxToDp(46),
    height: convertPxToDp(46),
    stroke: theme.colors.secondary,
  },
  'add-square': {
    type: 'svg',
    source: require('@assets/icons/add-square.js'),
    width: convertPxToDp(46),
    height: convertPxToDp(46),
    color: theme.colors.primary,
  },
  'add-square-outline': {
    type: 'svg',
    source: require('@assets/icons/add-square-outline.js'),
    width: convertPxToDp(46),
    height: convertPxToDp(46),
    stroke: theme.colors.secondary,
  },
  machine: {
    type: 'svg',
    source: require('@assets/icons/machine.js'),
    width: convertPxToDp(46),
    height: convertPxToDp(46),
    color: theme.colors.primary,
    stroke: theme.colors.primary,
  },
  'machine-outline': {
    type: 'svg',
    source: require('@assets/icons/machine-outline.js'),
    width: convertPxToDp(46),
    height: convertPxToDp(46),
    stroke: theme.colors.secondary,
  },
  additem: {
    type: 'svg',
    source: require('@assets/icons/additem.js'),
    width: convertPxToDp(46),
    height: convertPxToDp(46),
    color: theme.colors.primary,
    stroke: theme.colors.primary,
  },
  'additem-outline': {
    type: 'svg',
    source: require('@assets/icons/additem-outline.js'),
    width: convertPxToDp(46),
    height: convertPxToDp(46),
    stroke: theme.colors.secondary,
  },
  document: {
    type: 'svg',
    source: require('@assets/icons/document.js'),
    width: convertPxToDp(36.529),
    height: convertPxToDp(46),
    color: theme.colors.primary,
    stroke: theme.colors.primary,
  },
  'document-outline': {
    type: 'svg',
    source: require('@assets/icons/document-outline.js'),
    width: convertPxToDp(36.529),
    height: convertPxToDp(46),
    stroke: theme.colors.secondary,
  },
  'folder-add': {
    type: 'svg',
    source: require('@assets/icons/folder-add.js'),
    width: convertPxToDp(46),
    height: convertPxToDp(46),
    color: theme.colors.primary,
  },
  'folder-add-outline': {
    type: 'svg',
    source: require('@assets/icons/folder-add-outline.js'),
    width: convertPxToDp(46),
    height: convertPxToDp(46),
    stroke: theme.colors.secondary,
  },
  attach: {
    type: 'svg',
    source: require('@assets/icons/attach.js'),
    width: convertPxToDp(46),
    height: convertPxToDp(46),
    color: theme.colors.primary,
  },
  'attach-outline': {
    type: 'svg',
    source: require('@assets/icons/attach-outline.js'),
    width: convertPxToDp(46),
    height: convertPxToDp(46),
    color: theme.colors.secondary,
  },
  users: {
    type: 'svg',
    source: require('@assets/icons/users.js'),
    width: convertPxToDp(56),
    height: convertPxToDp(56),
    color: theme.colors.primary,
  },
  'users-outline': {
    type: 'svg',
    source: require('@assets/icons/users-outline.js'),
    width: convertPxToDp(56),
    height: convertPxToDp(56),
    color: theme.colors.secondary,
  },
  'card-chip-stop-hours': {
    type: 'svg',
    source: require('@assets/icons/stop-hours.js'),
    width: convertPxToDp(25),
    height: convertPxToDp(25),
    stroke: theme.colors.primary,
    opacity: 0.7,
  },
  'card-chip-working-hours': {
    type: 'svg',
    source: require('@assets/icons/working-hours.js'),
    width: convertPxToDp(25),
    height: convertPxToDp(25),
    stroke: theme.colors.primary,
    opacity: 0.7,
  },
  'card-chip-machine': {
    type: 'svg',
    source: require('@assets/icons/machine-outline.js'),
    width: convertPxToDp(27),
    height: convertPxToDp(27),
    stroke: theme.colors.primary,
    opacity: 0.7,
  },
  'table-view-add-square': {
    type: 'svg',
    source: require('@assets/icons/add-square.js'),
    width: convertPxToDp(28),
    height: convertPxToDp(28),
    color: theme.colors.primary,
  },
};

export default iconData;
